/**
 * toolConfig.js — All 60 ScrambleFix tools
 *
 * Each tool: { slug, title, description, category, icon, type, fn, options? }
 *
 * Types:
 *   transform — text in → text out
 *   extract   — text in → string[] out (displayed as chips)
 *   generate  — options → text out (no text input)
 *   analyze   — text in → stats object out
 *   ai        — text in → text out (async, needs API key)
 */

import * as T from './textUtils';
import * as AI from './aiUtils';

export const CATEGORIES = [
  { id: 'cleaning',       label: 'Text Cleaning',   icon: '🧹', color: '#3b82f6' },
  { id: 'extraction',     label: 'Extraction',       icon: '🔍', color: '#10b981' },
  { id: 'formatting',     label: 'Formatting',        icon: '✏️',  color: '#8b5cf6' },
  { id: 'encoding',       label: 'Encoding',          icon: '🔐', color: '#f59e0b' },
  { id: 'generators',     label: 'Generators',        icon: '⚡', color: '#ef4444' },
  { id: 'ai',             label: 'AI Tools',          icon: '🤖', color: '#ec4899' },
];

export const TOOLS = [

  // ── 1. TEXT CLEANING (12) ────────────────────────────────────────

  {
    slug: 'remove-blank-lines',
    title: 'Remove Blank Lines',
    description: 'Strip all empty and whitespace-only lines from your text instantly.',
    category: 'cleaning', icon: '📄', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Cleaned result',
    placeholder: 'Line one\n\nLine two\n\nLine three',
    fn: (text) => T.removeBlankLines(text),
  },
  {
    slug: 'remove-extra-spaces',
    title: 'Remove Extra Spaces',
    description: 'Collapse multiple spaces and tabs into single spaces. Trims each line.',
    category: 'cleaning', icon: '␣', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Cleaned result',
    placeholder: 'Too   many    spaces    here',
    fn: (text) => T.removeExtraSpaces(text),
  },
  {
    slug: 'remove-duplicate-lines',
    title: 'Remove Duplicate Lines',
    description: 'Remove duplicate lines from any list or block of text, keeping originals.',
    category: 'cleaning', icon: '🗂️', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Deduplicated result',
    placeholder: 'apple\nbanana\napple\nmango\nbanana',
    fn: (text) => T.removeDuplicateLines(text),
    options: [{ id:'caseSensitive', label:'Case-sensitive', type:'toggle', default:false }],
  },
  {
    slug: 'remove-punctuation',
    title: 'Remove Punctuation',
    description: 'Strip all punctuation marks from your text — commas, periods, quotes and more.',
    category: 'cleaning', icon: '!', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Cleaned result',
    placeholder: 'Hello, world! How are you?',
    fn: (text) => T.removePunctuation(text),
  },
  {
    slug: 'remove-numbers',
    title: 'Remove Numbers',
    description: 'Delete all numeric digits from your text, leaving only letters and symbols.',
    category: 'cleaning', icon: '🔢', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Cleaned result',
    placeholder: 'Product code: A123B456, Price: $9.99',
    fn: (text) => T.removeNumbers(text),
  },
  {
    slug: 'remove-emojis',
    title: 'Remove Emojis',
    description: 'Strip all emoji characters from text for clean, plain output.',
    category: 'cleaning', icon: '😶', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Cleaned result',
    placeholder: 'Hello 👋 world 🌍 have a great day 🎉',
    fn: (text) => T.removeEmojis(text),
  },
  {
    slug: 'remove-symbols',
    title: 'Remove Symbols',
    description: 'Keep only letters, numbers and spaces — strip everything else.',
    category: 'cleaning', icon: '※', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Cleaned result',
    placeholder: 'Hello @world! #test $100 ~fancy~',
    fn: (text) => T.removeSymbols(text),
  },
  {
    slug: 'remove-stopwords',
    title: 'Remove Stopwords',
    description: 'Remove common English filler words (the, a, is, are, etc.) from your text.',
    category: 'cleaning', icon: '🚫', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Cleaned result',
    placeholder: 'The quick brown fox jumps over the lazy dog',
    fn: (text) => T.removeStopwords(text),
  },
  {
    slug: 'trim-whitespace',
    title: 'Trim Whitespace',
    description: 'Remove leading and trailing whitespace from every line.',
    category: 'cleaning', icon: '✂️', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Trimmed result',
    placeholder: '   hello world   \n  another line  ',
    fn: (text) => T.trimWhitespace(text),
  },
  {
    slug: 'normalize-text',
    title: 'Normalize Text',
    description: 'Fix encoding, remove diacritics, normalize smart quotes and dashes.',
    category: 'cleaning', icon: '⚖️', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Normalized result',
    placeholder: 'Héllo wörld — "smart quotes" and… ellipsis',
    fn: (text) => T.normalizeText(text),
  },
  {
    slug: 'strip-html-tags',
    title: 'Strip HTML Tags',
    description: 'Remove all HTML tags from text, leaving only the raw content.',
    category: 'cleaning', icon: '</>', type: 'transform',
    inputLabel: 'Paste HTML', outputLabel: 'Plain text',
    placeholder: '<h1>Hello</h1><p>This is <strong>HTML</strong> text.</p>',
    fn: (text) => T.stripHtmlTags(text),
  },
  {
    slug: 'clean-json',
    title: 'Clean JSON',
    description: 'Validate and prettify any JSON — instantly formatted with 2-space indentation.',
    category: 'cleaning', icon: '{}', type: 'transform',
    inputLabel: 'Paste your JSON', outputLabel: 'Formatted JSON',
    placeholder: '{"name":"ScrambleFix","tools":60,"active":true}',
    fn: (text) => T.cleanJson(text),
  },

  // ── 2. EXTRACTION (10) ───────────────────────────────────────────

  {
    slug: 'extract-emails',
    title: 'Extract Emails',
    description: 'Pull all email addresses out of any block of text instantly.',
    category: 'extraction', icon: '📧', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Emails found',
    placeholder: 'Contact us at hello@example.com or support@scramblefix.io for help.',
    fn: (text) => T.extractEmails(text),
  },
  {
    slug: 'extract-urls',
    title: 'Extract URLs',
    description: 'Find and extract all https:// and http:// links from any text.',
    category: 'extraction', icon: '🔗', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'URLs found',
    placeholder: 'Visit https://scramblefix.io or https://cloudflare.com for more info.',
    fn: (text) => T.extractUrls(text),
  },
  {
    slug: 'extract-phone-numbers',
    title: 'Extract Phone Numbers',
    description: 'Extract all phone numbers from text — handles international formats.',
    category: 'extraction', icon: '📱', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Phone numbers found',
    placeholder: 'Call us at +1-800-555-0199 or (212) 555-0100.',
    fn: (text) => T.extractPhoneNumbers(text),
  },
  {
    slug: 'extract-hashtags',
    title: 'Extract Hashtags',
    description: 'Pull every #hashtag out of social media posts or any text.',
    category: 'extraction', icon: '#️⃣', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Hashtags found',
    placeholder: 'Loving this! #coding #tools #productivity #ScrambleFix',
    fn: (text) => T.extractHashtags(text),
  },
  {
    slug: 'extract-mentions',
    title: 'Extract Mentions',
    description: 'Extract all @mentions from tweets, posts or any social content.',
    category: 'extraction', icon: '@', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Mentions found',
    placeholder: 'Thanks @johndoe and @janesmith for the help! @ScrambleFix rocks.',
    fn: (text) => T.extractMentions(text),
  },
  {
    slug: 'extract-numbers',
    title: 'Extract Numbers',
    description: 'Find every number — integer or decimal — hidden in any text.',
    category: 'extraction', icon: '🔢', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Numbers found',
    placeholder: 'Revenue grew 23.5% to $4.2 billion, with 1,300 new customers.',
    fn: (text) => T.extractNumbers(text),
  },
  {
    slug: 'extract-dates',
    title: 'Extract Dates',
    description: 'Find dates in various formats — MM/DD/YYYY, Month DD YYYY, and more.',
    category: 'extraction', icon: '📅', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Dates found',
    placeholder: 'Meeting on 25/12/2024. Launch: January 15, 2025. Deadline 03-31-2025.',
    fn: (text) => T.extractDates(text),
  },
  {
    slug: 'extract-ip-addresses',
    title: 'Extract IP Addresses',
    description: 'Pull all IPv4 addresses from log files, configs or any text.',
    category: 'extraction', icon: '🌐', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'IP addresses found',
    placeholder: 'Access from 192.168.1.1 and 10.0.0.254. Blocked: 203.0.113.42',
    fn: (text) => T.extractIpAddresses(text),
  },
  {
    slug: 'extract-json-objects',
    title: 'Extract JSON Objects',
    description: 'Find and extract all valid JSON objects embedded in any text.',
    category: 'extraction', icon: '{}', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'JSON objects found',
    placeholder: 'Log: {"user":"alice","action":"login"} and {"user":"bob","action":"logout"}',
    fn: (text) => T.extractJsonObjects(text),
  },
  {
    slug: 'extract-keywords',
    title: 'Extract Keywords',
    description: 'Identify the most frequent and significant keywords from any text.',
    category: 'extraction', icon: '🔑', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Keywords found',
    placeholder: 'Paste an article, blog post or any longer text to extract keywords.',
    fn: (text) => T.extractKeywords(text),
  },

  // ── 3. FORMATTING & TRANSFORMATION (14) ─────────────────────────

  {
    slug: 'case-converter',
    title: 'Case Converter',
    description: 'Convert text to UPPERCASE, lowercase, Title Case, camelCase, snake_case and more.',
    category: 'formatting', icon: 'Aa', type: 'multi-transform',
    inputLabel: 'Enter your text', outputLabel: 'All formats',
    placeholder: 'Type something to see all 9 case formats update live...',
    fn: (text, {mode}) => {
      const f = T.CASE_FORMATS.find(f=>f.id===mode);
      return f ? f.fn(text) : text;
    },
    options: [{ id:'mode', label:'Format', type:'select', default:'upper', choices: T.CASE_FORMATS.map(f=>({value:f.id,label:f.label})) }],
  },
  {
    slug: 'text-reverser',
    title: 'Text Reverser',
    description: 'Reverse entire text, each word individually, or reverse the word order.',
    category: 'formatting', icon: '↩️', type: 'transform',
    inputLabel: 'Enter your text', outputLabel: 'Reversed result',
    placeholder: 'The quick brown fox',
    fn: (text, {mode='full'}) => T.reverseText(text, mode),
    options: [{ id:'mode', label:'Reverse mode', type:'select', default:'full', choices:[{value:'full',label:'Reverse all characters'},{value:'words',label:'Reverse each word'},{value:'order',label:'Reverse word order'}] }],
  },
  {
    slug: 'word-sorter',
    title: 'Word Sorter',
    description: 'Sort any list of words A–Z, Z–A, by length, or in reverse.',
    category: 'formatting', icon: '↕️', type: 'transform',
    inputLabel: 'Enter words (space or comma separated)', outputLabel: 'Sorted result',
    placeholder: 'apple banana cherry mango orange kiwi',
    fn: (text, {mode='az'}) => T.sortWords(text.trim().split(/[\s,]+/).filter(Boolean), mode).join(' '),
    options: [{ id:'mode', label:'Sort order', type:'select', default:'az', choices:[{value:'az',label:'A → Z'},{value:'za',label:'Z → A'},{value:'short',label:'Shortest first'},{value:'long',label:'Longest first'},{value:'rev',label:'Reverse order'}] }],
  },
  {
    slug: 'line-sorter',
    title: 'Line Sorter',
    description: 'Sort lines alphabetically, by length, or in reverse — one click.',
    category: 'formatting', icon: '📋', type: 'transform',
    inputLabel: 'Paste your lines', outputLabel: 'Sorted lines',
    placeholder: 'Zebra\nApple\nMango\nBanana',
    fn: (text, {mode='az'}) => T.sortLines(text, mode),
    options: [{ id:'mode', label:'Sort order', type:'select', default:'az', choices:[{value:'az',label:'A → Z'},{value:'za',label:'Z → A'},{value:'short',label:'Shortest first'},{value:'long',label:'Longest first'},{value:'rev',label:'Reverse'}] }],
  },
  {
    slug: 'sentence-shuffler',
    title: 'Sentence Shuffler',
    description: 'Randomly shuffle words, sentences, or individual letters in any text.',
    category: 'formatting', icon: '🔀', type: 'transform',
    inputLabel: 'Enter your text', outputLabel: 'Shuffled result',
    placeholder: 'The quick brown fox jumps over the lazy dog.',
    fn: (text, {mode='words'}) => T.doShuffle(text, mode),
    options: [{ id:'mode', label:'Shuffle mode', type:'select', default:'words', choices:[{value:'words',label:'Shuffle words'},{value:'sentences',label:'Shuffle sentences'},{value:'letters',label:'Scramble letters'}] }],
  },
  {
    slug: 'line-shuffler',
    title: 'Line Shuffler',
    description: 'Randomly reorder every line in your text. Perfect for randomizing lists.',
    category: 'formatting', icon: '🎲', type: 'transform',
    inputLabel: 'Paste your lines', outputLabel: 'Shuffled result',
    placeholder: 'First line\nSecond line\nThird line\nFourth line',
    fn: (text) => T.doShuffle(text, 'lines'),
  },
  {
    slug: 'word-counter',
    title: 'Word Counter',
    description: 'Count words, characters, sentences, paragraphs, lines and reading time.',
    category: 'formatting', icon: '📊', type: 'analyze',
    inputLabel: 'Paste your text', outputLabel: 'Statistics',
    placeholder: 'Paste any text and get detailed statistics instantly...',
    fn: (text) => T.countWords(text),
  },
  {
    slug: 'character-counter',
    title: 'Character Counter',
    description: 'Count total characters, characters without spaces, and per-character breakdown.',
    category: 'formatting', icon: '🔤', type: 'analyze',
    inputLabel: 'Enter your text', outputLabel: 'Character stats',
    placeholder: 'Type or paste to count characters instantly...',
    fn: (text) => {
      const freq={};text.split('').forEach(c=>{freq[c]=(freq[c]||0)+1;});
      return {chars:text.length,noSpaces:text.replace(/\s/g,'').length,letters:text.replace(/[^a-zA-Z]/g,'').length,breakdown:Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,20)};
    },
  },
  {
    slug: 'word-frequency-analyzer',
    title: 'Word Frequency Analyzer',
    description: 'See how many times each word appears, sorted by frequency.',
    category: 'formatting', icon: '📈', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Word frequencies',
    placeholder: 'Paste any text to analyze word frequency...',
    fn: (text, {ignoreStopwords=true}) => T.wordFrequency(text, ignoreStopwords),
    options: [{ id:'ignoreStopwords', label:'Ignore common words', type:'toggle', default:true }],
  },
  {
    slug: 'text-indenter',
    title: 'Text Indenter',
    description: 'Add consistent indentation to every line — choose 2, 4 or custom spaces.',
    category: 'formatting', icon: '→', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Indented result',
    placeholder: 'function hello() {\nconsole.log("world");\n}',
    fn: (text, {spaces=2}) => T.indentText(text, Number(spaces)),
    options: [{ id:'spaces', label:'Spaces', type:'select', default:'2', choices:[{value:'2',label:'2 spaces'},{value:'4',label:'4 spaces'},{value:'8',label:'8 spaces'}] }],
  },
  {
    slug: 'text-de-indenter',
    title: 'Text De-Indenter',
    description: 'Remove all leading spaces and tabs from every line.',
    category: 'formatting', icon: '←', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'De-indented result',
    placeholder: '    function hello() {\n        console.log("world");\n    }',
    fn: (text) => T.deIndentText(text),
  },
  {
    slug: 'sort-paragraphs',
    title: 'Sort Paragraphs',
    description: 'Sort paragraphs (separated by blank lines) alphabetically or in reverse.',
    category: 'formatting', icon: '¶', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Sorted paragraphs',
    placeholder: 'Zebra paragraph.\n\nApple paragraph.\n\nMango paragraph.',
    fn: (text, {mode='az'}) => T.sortParagraphs(text, mode),
    options: [{ id:'mode', label:'Order', type:'select', default:'az', choices:[{value:'az',label:'A → Z'},{value:'za',label:'Z → A'},{value:'rev',label:'Reverse'}] }],
  },
  {
    slug: 'shuffle-paragraphs',
    title: 'Shuffle Paragraphs',
    description: 'Randomly reorder paragraphs in your text.',
    category: 'formatting', icon: '🃏', type: 'transform',
    inputLabel: 'Paste your text', outputLabel: 'Shuffled paragraphs',
    placeholder: 'First paragraph here.\n\nSecond paragraph here.\n\nThird paragraph here.',
    fn: (text) => T.shuffleParagraphs(text),
  },
  {
    slug: 'split-text',
    title: 'Split Text',
    description: 'Split any text by a custom delimiter — comma, pipe, newline, or any character.',
    category: 'formatting', icon: '✂️', type: 'extract',
    inputLabel: 'Paste your text', outputLabel: 'Split parts',
    placeholder: 'apple,banana,cherry,mango,orange',
    fn: (text, {delimiter=','}) => T.splitText(text, delimiter),
    options: [{ id:'delimiter', label:'Split by', type:'select', default:',', choices:[{value:',',label:'Comma'},{value:'\n',label:'New line'},{value:'|',label:'Pipe |'},{value:';',label:'Semicolon'},{value:'\t',label:'Tab'}] }],
  },

  // ── 4. ENCODING / DECODING (8) ───────────────────────────────────

  {
    slug: 'base64-encode',
    title: 'Base64 Encode',
    description: 'Encode any text to Base64 format instantly. Supports Unicode.',
    category: 'encoding', icon: '🔒', type: 'transform',
    inputLabel: 'Text to encode', outputLabel: 'Base64 output',
    placeholder: 'Hello, ScrambleFix!',
    fn: (text) => T.base64Encode(text),
  },
  {
    slug: 'base64-decode',
    title: 'Base64 Decode',
    description: 'Decode any Base64 string back to plain text.',
    category: 'encoding', icon: '🔓', type: 'transform',
    inputLabel: 'Base64 to decode', outputLabel: 'Decoded text',
    placeholder: 'SGVsbG8sIFNjcmFtYmxlRml4IQ==',
    fn: (text) => T.base64Decode(text),
  },
  {
    slug: 'url-encode',
    title: 'URL Encode',
    description: 'Percent-encode text for safe use in URLs and query strings.',
    category: 'encoding', icon: '🌐', type: 'transform',
    inputLabel: 'Text to encode', outputLabel: 'URL-encoded output',
    placeholder: 'hello world & more = stuff',
    fn: (text) => T.urlEncode(text),
  },
  {
    slug: 'url-decode',
    title: 'URL Decode',
    description: 'Decode percent-encoded URLs and query strings back to plain text.',
    category: 'encoding', icon: '🌐', type: 'transform',
    inputLabel: 'URL to decode', outputLabel: 'Decoded text',
    placeholder: 'hello%20world%20%26%20more%20%3D%20stuff',
    fn: (text) => T.urlDecode(text),
  },
  {
    slug: 'html-encode',
    title: 'HTML Encode',
    description: 'Convert HTML special characters to safe entity equivalents.',
    category: 'encoding', icon: '🛡️', type: 'transform',
    inputLabel: 'Text to encode', outputLabel: 'HTML entities',
    placeholder: '<script>alert("XSS")</script> & more "stuff"',
    fn: (text) => T.htmlEncode(text),
  },
  {
    slug: 'html-decode',
    title: 'HTML Decode',
    description: 'Convert HTML entities (&lt; &gt; &amp;) back to readable characters.',
    category: 'encoding', icon: '📄', type: 'transform',
    inputLabel: 'HTML entities to decode', outputLabel: 'Decoded text',
    placeholder: '&lt;script&gt;alert(&quot;XSS&quot;)&lt;/script&gt;',
    fn: (text) => T.htmlDecode(text),
  },
  {
    slug: 'jwt-decoder',
    title: 'JWT Decoder',
    description: 'Decode and inspect any JWT token — view header, payload and claims.',
    category: 'encoding', icon: '🎫', type: 'transform',
    inputLabel: 'Paste your JWT token', outputLabel: 'Decoded JWT',
    placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
    fn: (text) => T.decodeJwt(text),
  },
  {
    slug: 'morse-code-converter',
    title: 'Morse Code Converter',
    description: 'Convert text to Morse code or decode Morse back to text.',
    category: 'encoding', icon: '📡', type: 'transform',
    inputLabel: 'Enter text or Morse code', outputLabel: 'Converted result',
    placeholder: 'SOS',
    fn: (text, {direction='encode'}) => direction==='encode' ? T.morseEncode(text) : T.morseDecode(text),
    options: [{ id:'direction', label:'Direction', type:'select', default:'encode', choices:[{value:'encode',label:'Text → Morse'},{value:'decode',label:'Morse → Text'}] }],
  },

  // ── 5. GENERATORS (10) ───────────────────────────────────────────

  {
    slug: 'password-generator',
    title: 'Password Generator',
    description: 'Generate strong, random passwords with custom length and character sets.',
    category: 'generators', icon: '🔑', type: 'generate',
    outputLabel: 'Generated password',
    fn: (_, opts) => T.generatePassword({
      length:  Number(opts?.length  || 16),
      upper:   opts?.upper   !== false,
      lower:   opts?.lower   !== false,
      digits:  opts?.digits  !== false,
      symbols: opts?.symbols === true,
    }),
    options: [
      { id:'length',  label:'Length',  type:'select', default:'16', choices:[{value:'8',label:'8'},{value:'12',label:'12'},{value:'16',label:'16'},{value:'24',label:'24'},{value:'32',label:'32'}] },
      { id:'upper',   label:'Uppercase (A-Z)',   type:'toggle', default:true },
      { id:'lower',   label:'Lowercase (a-z)',   type:'toggle', default:true },
      { id:'digits',  label:'Numbers (0-9)',     type:'toggle', default:true },
      { id:'symbols', label:'Symbols (!@#...)',  type:'toggle', default:false },
    ],
  },
  {
    slug: 'username-generator',
    title: 'Username Generator',
    description: 'Generate unique, creative usernames — adjective + noun + number combos.',
    category: 'generators', icon: '👤', type: 'generate',
    outputLabel: 'Generated usernames',
    fn: (_, opts) => Array.from({length: Number(opts?.count||5)}, ()=>T.generateUsername()).join('\n'),
    options: [{ id:'count', label:'Count', type:'select', default:'5', choices:[{value:'1',label:'1'},{value:'5',label:'5'},{value:'10',label:'10'}] }],
  },
  {
    slug: 'random-word-generator',
    title: 'Random Word Generator',
    description: 'Generate random English words for games, brainstorming and creative writing.',
    category: 'generators', icon: '📝', type: 'generate',
    outputLabel: 'Random words',
    fn: (_, opts) => T.generateRandomWord(Number(opts?.count||10)),
    options: [{ id:'count', label:'Count', type:'select', default:'10', choices:[{value:'5',label:'5'},{value:'10',label:'10'},{value:'20',label:'20'},{value:'50',label:'50'}] }],
  },
  {
    slug: 'lorem-ipsum-generator',
    title: 'Lorem Ipsum Generator',
    description: 'Generate placeholder Lorem Ipsum text — choose paragraphs and sentence count.',
    category: 'generators', icon: '📖', type: 'generate',
    outputLabel: 'Lorem ipsum text',
    fn: (_, opts) => T.generateLoremIpsum({paragraphs:Number(opts?.paragraphs||3), sentences:Number(opts?.sentences||5)}),
    options: [
      { id:'paragraphs', label:'Paragraphs', type:'select', default:'3', choices:[{value:'1',label:'1'},{value:'3',label:'3'},{value:'5',label:'5'},{value:'10',label:'10'}] },
      { id:'sentences',  label:'Sentences each', type:'select', default:'5', choices:[{value:'3',label:'3'},{value:'5',label:'5'},{value:'8',label:'8'}] },
    ],
  },
  {
    slug: 'random-sentence-generator',
    title: 'Random Sentence Generator',
    description: 'Generate random sentences for filler content, testing or creative prompts.',
    category: 'generators', icon: '💬', type: 'generate',
    outputLabel: 'Random sentences',
    fn: (_, opts) => T.generateRandomSentence(Number(opts?.count||5)),
    options: [{ id:'count', label:'Count', type:'select', default:'5', choices:[{value:'1',label:'1'},{value:'5',label:'5'},{value:'10',label:'10'}] }],
  },
  {
    slug: 'random-paragraph-generator',
    title: 'Random Paragraph Generator',
    description: 'Generate random paragraphs — useful for design mockups and content testing.',
    category: 'generators', icon: '📰', type: 'generate',
    outputLabel: 'Random paragraphs',
    fn: (_, opts) => T.generateRandomParagraph(Number(opts?.count||3)),
    options: [{ id:'count', label:'Count', type:'select', default:'3', choices:[{value:'1',label:'1'},{value:'3',label:'3'},{value:'5',label:'5'}] }],
  },
  {
    slug: 'random-number-generator',
    title: 'Random Number Generator',
    description: 'Generate random numbers within any range — integers or decimals.',
    category: 'generators', icon: '🎲', type: 'generate',
    outputLabel: 'Random numbers',
    fn: (_, opts) => T.generateRandomNumber({min:Number(opts?.min||1),max:Number(opts?.max||100),count:Number(opts?.count||1),decimals:Number(opts?.decimals||0)}),
    options: [
      { id:'min',      label:'Min',      type:'number', default:'1' },
      { id:'max',      label:'Max',      type:'number', default:'100' },
      { id:'count',    label:'Count',    type:'select', default:'1', choices:[{value:'1',label:'1'},{value:'5',label:'5'},{value:'10',label:'10'}] },
      { id:'decimals', label:'Decimals', type:'select', default:'0', choices:[{value:'0',label:'0'},{value:'2',label:'2'},{value:'4',label:'4'}] },
    ],
  },
  {
    slug: 'random-emoji-generator',
    title: 'Random Emoji Generator',
    description: 'Generate random emoji for fun, testing or social media content.',
    category: 'generators', icon: '🎭', type: 'generate',
    outputLabel: 'Random emojis',
    fn: (_, opts) => T.generateRandomEmoji(Number(opts?.count||10)),
    options: [{ id:'count', label:'Count', type:'select', default:'10', choices:[{value:'5',label:'5'},{value:'10',label:'10'},{value:'20',label:'20'}] }],
  },
  {
    slug: 'random-color-generator',
    title: 'Random Color Generator',
    description: 'Generate random colors in HEX, RGB or HSL format.',
    category: 'generators', icon: '🎨', type: 'generate',
    outputLabel: 'Random colors',
    fn: (_, opts) => T.generateRandomColor({format:opts?.format||'hex',count:Number(opts?.count||5)}),
    options: [
      { id:'format', label:'Format', type:'select', default:'hex', choices:[{value:'hex',label:'HEX'},{value:'rgb',label:'RGB'},{value:'hsl',label:'HSL'}] },
      { id:'count',  label:'Count',  type:'select', default:'5',   choices:[{value:'1',label:'1'},{value:'5',label:'5'},{value:'10',label:'10'}] },
    ],
  },
  {
    slug: 'uuid-generator',
    title: 'UUID Generator',
    description: 'Generate cryptographically random UUID v4 identifiers.',
    category: 'generators', icon: '🆔', type: 'generate',
    outputLabel: 'Generated UUIDs',
    fn: (_, opts) => T.generateUuid(Number(opts?.count||1)),
    options: [{ id:'count', label:'Count', type:'select', default:'1', choices:[{value:'1',label:'1'},{value:'5',label:'5'},{value:'10',label:'10'}] }],
  },

  // ── 6. AI-POWERED (6) ────────────────────────────────────────────

  {
    slug: 'ai-rewrite',
    title: 'AI Rewrite',
    description: 'Rewrite any text to be more engaging, compelling and polished using AI.',
    category: 'ai', icon: '✨', type: 'ai',
    inputLabel: 'Text to rewrite', outputLabel: 'Rewritten text',
    placeholder: 'Paste the text you want to rewrite...',
    fn: (text, _opts, apiKey) => AI.aiRewrite(text, apiKey),
  },
  {
    slug: 'ai-grammar-fix',
    title: 'AI Grammar Fix',
    description: 'Fix all grammar, spelling and punctuation errors in your text using AI.',
    category: 'ai', icon: '✏️', type: 'ai',
    inputLabel: 'Text to fix', outputLabel: 'Fixed text',
    placeholder: 'Paste the text with grammar errors...',
    fn: (text, _opts, apiKey) => AI.aiGrammarFix(text, apiKey),
  },
  {
    slug: 'ai-clarity-improve',
    title: 'AI Clarity Improve',
    description: 'Make your writing clearer, simpler and easier to read with AI.',
    category: 'ai', icon: '💡', type: 'ai',
    inputLabel: 'Text to improve', outputLabel: 'Improved text',
    placeholder: 'Paste confusing or complex text here...',
    fn: (text, _opts, apiKey) => AI.aiClarityImprove(text, apiKey),
  },
  {
    slug: 'ai-tone-change',
    title: 'AI Tone Change',
    description: 'Change the tone of your text — professional, casual, friendly, formal and more.',
    category: 'ai', icon: '🎭', type: 'ai',
    inputLabel: 'Text to adjust', outputLabel: 'Tone-adjusted text',
    placeholder: 'Paste your text here...',
    fn: (text, opts, apiKey) => AI.aiToneChange(text, apiKey, { tone: opts?.tone || 'professional' }),
    options: [{ id:'tone', label:'Target tone', type:'select', default:'professional', choices:[{value:'professional',label:'Professional'},{value:'casual',label:'Casual'},{value:'friendly',label:'Friendly'},{value:'formal',label:'Formal'},{value:'persuasive',label:'Persuasive'},{value:'concise',label:'Concise'}] }],
  },
  {
    slug: 'ai-summarizer',
    title: 'AI Summarizer',
    description: 'Summarize any long text into 2–3 clear, concise sentences using AI.',
    category: 'ai', icon: '📋', type: 'ai',
    inputLabel: 'Text to summarize', outputLabel: 'Summary',
    placeholder: 'Paste a long article, document or text to summarize...',
    fn: (text, _opts, apiKey) => AI.aiSummarize(text, apiKey),
  },
  {
    slug: 'ai-paraphraser',
    title: 'AI Paraphraser',
    description: 'Rephrase your text with different words and structure using AI.',
    category: 'ai', icon: '🔄', type: 'ai',
    inputLabel: 'Text to paraphrase', outputLabel: 'Paraphrased text',
    placeholder: 'Paste the text you want to paraphrase...',
    fn: (text, _opts, apiKey) => AI.aiParaphrase(text, apiKey),
  },

];

// Helper lookups
export const TOOL_BY_SLUG = Object.fromEntries(TOOLS.map(t => [t.slug, t]));
export const TOOLS_BY_CATEGORY = CATEGORIES.reduce((acc, cat) => {
  acc[cat.id] = TOOLS.filter(t => t.category === cat.id);
  return acc;
}, {});
